WITH ANALYTICS AS (
    SELECT COUNT(*) AS TRANSACTIONS_IN_ANALYTICS
    FROM {{ ref('fact_transaction') }}
),
REPORTING AS (
    SELECT COUNT(ID) AS TRANSACTIONS_IN_REPORTING
    FROM {{ ref('transaction') }}
)
SELECT *
FROM ANALYTICS, REPORTING
WHERE ANALYTICS.TRANSACTIONS_IN_ANALYTICS != REPORTING.TRANSACTIONS_IN_REPORTING 
