WITH TRANSFORM AS (
    SELECT COUNT(ID) AS TRANSACTIONS_IN_TRANSFORM
    FROM {{ ref('transaction') }}
),
ANALYTICS AS (
    SELECT COUNT(*) AS TRANSACTIONS_IN_ANALYTICS
    FROM {{ ref('fact_transaction') }}
)
SELECT *
FROM TRANSFORM, ANALYTICS
WHERE TRANSFORM.TRANSACTIONS_IN_TRANSFORM != ANALYTICS.TRANSACTIONS_IN_ANALYTICS
