
--Top 10 products sold

SELECT
    PRODUCT_SKU,
    COUNT(*) AS TOTAL_QUANTITY,
    SUM(AMOUNT) AS TOTAL_AMOUNT
FROM {{ ref('transaction_performance') }}
GROUP BY PRODUCT_SKU
ORDER BY TOTAL_QUANTITY DESC, TOTAL_AMOUNT DESC
LIMIT 10