
--Percentage of transactions per device type

SELECT
    DEVICE_TYPE,
    ROUND(COUNT(DISTINCT ID) * 100.00 / (SELECT COUNT(DISTINCT ID) FROM SUMUP."REPORTING".TRANSACTION_PERFORMANCE), 2) || '%' AS PCT_TRANSACTIONS
FROM {{ ref('transaction_performance') }}
GROUP BY DEVICE_TYPE
ORDER BY PCT_TRANSACTIONS DESC