name: Lint SQL with SQLFluff

on:
  push:
    paths:
      - 'models/**/*.sql'
      - '.sqlfluff'
  pull_request:
    paths:
      - 'models/**/*.sql'
      - '.sqlfluff'

jobs:
  lint-sql:
    name: SQLFluff Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt & SQLFluff
        run: |
          python -m pip install --upgrade pip
          pip install sqlfluff sqlfluff-templater-dbt dbt-postgres

      - name: Set up fake dbt profile (no real DB needed)
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          project_sumup:
            target: dev
            outputs:
              dev:
                type: postgres
                host: localhost
                user: fake
                pass: fake
                port: 5432
                dbname: fake
                schema: public
                threads: 1
          EOF

      - name: Lint models using SQLFluff with dbt templater
        run: sqlfluff lint models/ --dialect postgres --disable-progress-bar || true
